version: '3.9'

services:
  php-env:
    build: .
    volumes:
      - ./src:/var/www/html
      - ./server.crt:/etc/ssl/certs/server.crt   # Tambahkan sertifikat ke kontainer
      - ./server.key:/etc/ssl/private/server.key # Tambahkan private key ke kontainer
    ports:
      - 8080:80
      - 443:443   # Tambahkan port HTTPS

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql_db
