version: '3.9'  # Pastikan menambahkan versi jika Anda menggunakan versi Docker Compose yang lebih baru
services:
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
