name: Deploy PHP App to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code from repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Google Cloud SDK with service account credentials
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    # Authenticate using the service account key
    - name: Authenticate with Google Cloud
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > /tmp/gcp-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json

    # Configure Docker for Google Cloud
    - name: Configure Docker for Google Cloud
      run: |
        gcloud auth configure-docker

    # Submit build to Google Cloud Build
    - name: Submit build to Google Cloud Build
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/website-perpustakaan:latest
